/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_BANG_DASH_DASH = 1,
  anon_sym_SLASH = 2,
  anon_sym_DASH_DASH_GT = 3,
  sym_tag = 4,
  anon_sym_field = 5,
  anon_sym_EQ = 6,
  sym_key = 7,
  aux_sym_string_token1 = 8,
  aux_sym_string_token2 = 9,
  sym_bare_value = 10,
  aux_sym_text_token1 = 11,
  anon_sym_LT = 12,
  sym_source = 13,
  sym_marker = 14,
  sym_field_line = 15,
  sym_attribute = 16,
  sym_value = 17,
  sym_string = 18,
  sym_text = 19,
  aux_sym_source_repeat1 = 20,
  aux_sym_source_repeat2 = 21,
  aux_sym_source_repeat3 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_tag] = "tag",
  [anon_sym_field] = "field",
  [anon_sym_EQ] = "=",
  [sym_key] = "key",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym_bare_value] = "bare_value",
  [aux_sym_text_token1] = "text_token1",
  [anon_sym_LT] = "<",
  [sym_source] = "source",
  [sym_marker] = "marker",
  [sym_field_line] = "field_line",
  [sym_attribute] = "attribute",
  [sym_value] = "value",
  [sym_string] = "string",
  [sym_text] = "text",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_source_repeat2] = "source_repeat2",
  [aux_sym_source_repeat3] = "source_repeat3",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_tag] = sym_tag,
  [anon_sym_field] = anon_sym_field,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_key] = sym_key,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_bare_value] = sym_bare_value,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [anon_sym_LT] = anon_sym_LT,
  [sym_source] = sym_source,
  [sym_marker] = sym_marker,
  [sym_field_line] = sym_field_line,
  [sym_attribute] = sym_attribute,
  [sym_value] = sym_value,
  [sym_string] = sym_string,
  [sym_text] = sym_text,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_source_repeat2] = aux_sym_source_repeat2,
  [aux_sym_source_repeat3] = aux_sym_source_repeat3,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_field] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_bare_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_field_line] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_repeat3] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
  [1] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 21,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 25,
  [28] = 26,
  [29] = 24,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '"', 2,
        '\'', 3,
        '-', 4,
        '/', 34,
        '<', 51,
        '=', 39,
        'f', 21,
        'm', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(3);
      if (lookahead == '-') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(48);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(32);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '>') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(45);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(45);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '=') ADVANCE(45);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '=') ADVANCE(45);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '=') ADVANCE(45);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '>') ADVANCE(49);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(49);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(35);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(37);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(23);
      END_STATE();
    case 20:
      if (lookahead == 'h') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 25:
      if (lookahead == 'x') ADVANCE(14);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '-') ADVANCE(49);
      END_STATE();
    case 28:
      if (eof) ADVANCE(31);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '<') ADVANCE(40);
      if (lookahead == '=') ADVANCE(39);
      if (lookahead == 'f') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(45);
      END_STATE();
    case 29:
      if (eof) ADVANCE(31);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '=') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(29);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(45);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      if (lookahead == '<') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (lookahead != 0) ADVANCE(50);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(45);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '-') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_field);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_field);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '=') ADVANCE(45);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '!') ADVANCE(46);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < ' ' || '"' < lookahead) &&
          lookahead != '=') ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == 'd') ADVANCE(38);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '=') ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == 'e') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '=') ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == 'i') ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '=') ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == 'l') ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '=') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '=') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '=') ADVANCE(45);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_bare_value);
      if (lookahead == '-') ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(13);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 30},
  [3] = {.lex_state = 30},
  [4] = {.lex_state = 30},
  [5] = {.lex_state = 28},
  [6] = {.lex_state = 28},
  [7] = {.lex_state = 29},
  [8] = {.lex_state = 28},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 29},
  [12] = {.lex_state = 30},
  [13] = {.lex_state = 30},
  [14] = {.lex_state = 29},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 29},
  [18] = {.lex_state = 29},
  [19] = {.lex_state = 29},
  [20] = {.lex_state = 30},
  [21] = {.lex_state = 29},
  [22] = {.lex_state = 30},
  [23] = {.lex_state = 28},
  [24] = {.lex_state = 29},
  [25] = {.lex_state = 29},
  [26] = {.lex_state = 29},
  [27] = {.lex_state = 28},
  [28] = {.lex_state = 28},
  [29] = {.lex_state = 28},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
    [sym_tag] = ACTIONS(1),
    [anon_sym_field] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(32),
    [sym_marker] = STATE(2),
    [sym_field_line] = STATE(16),
    [sym_attribute] = STATE(11),
    [aux_sym_source_repeat1] = STATE(16),
    [aux_sym_source_repeat2] = STATE(11),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(3),
    [anon_sym_field] = ACTIONS(5),
    [sym_key] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(13), 1,
      aux_sym_text_token1,
    ACTIONS(15), 1,
      anon_sym_LT,
    STATE(3), 3,
      sym_marker,
      sym_text,
      aux_sym_source_repeat3,
  [18] = 5,
    ACTIONS(11), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(13), 1,
      aux_sym_text_token1,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(4), 3,
      sym_marker,
      sym_text,
      aux_sym_source_repeat3,
  [36] = 5,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(24), 1,
      aux_sym_text_token1,
    ACTIONS(27), 1,
      anon_sym_LT,
    STATE(4), 3,
      sym_marker,
      sym_text,
      aux_sym_source_repeat3,
  [54] = 4,
    ACTIONS(30), 1,
      ts_builtin_sym_end,
    ACTIONS(32), 1,
      anon_sym_field,
    ACTIONS(34), 1,
      sym_key,
    STATE(5), 2,
      sym_attribute,
      aux_sym_source_repeat2,
  [68] = 4,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      anon_sym_field,
    ACTIONS(41), 1,
      sym_key,
    STATE(5), 2,
      sym_attribute,
      aux_sym_source_repeat2,
  [82] = 3,
    ACTIONS(43), 1,
      sym_key,
    ACTIONS(30), 2,
      ts_builtin_sym_end,
      anon_sym_DASH_DASH_GT,
    STATE(7), 2,
      sym_attribute,
      aux_sym_source_repeat2,
  [94] = 4,
    ACTIONS(41), 1,
      sym_key,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 1,
      anon_sym_field,
    STATE(6), 2,
      sym_attribute,
      aux_sym_source_repeat2,
  [108] = 4,
    ACTIONS(52), 1,
      sym_bare_value,
    STATE(24), 1,
      sym_string,
    STATE(26), 1,
      sym_value,
    ACTIONS(50), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [122] = 4,
    ACTIONS(56), 1,
      sym_bare_value,
    STATE(28), 1,
      sym_value,
    STATE(29), 1,
      sym_string,
    ACTIONS(54), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [136] = 3,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      sym_key,
    STATE(7), 2,
      sym_attribute,
      aux_sym_source_repeat2,
  [147] = 2,
    ACTIONS(62), 1,
      anon_sym_LT,
    ACTIONS(60), 3,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      aux_sym_text_token1,
  [156] = 2,
    ACTIONS(66), 1,
      anon_sym_LT,
    ACTIONS(64), 3,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      aux_sym_text_token1,
  [165] = 3,
    ACTIONS(58), 1,
      sym_key,
    ACTIONS(68), 1,
      anon_sym_DASH_DASH_GT,
    STATE(18), 2,
      sym_attribute,
      aux_sym_source_repeat2,
  [176] = 3,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    ACTIONS(72), 1,
      anon_sym_field,
    STATE(15), 2,
      sym_field_line,
      aux_sym_source_repeat1,
  [187] = 3,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      anon_sym_field,
    STATE(15), 2,
      sym_field_line,
      aux_sym_source_repeat1,
  [198] = 3,
    ACTIONS(58), 1,
      sym_key,
    ACTIONS(77), 1,
      anon_sym_DASH_DASH_GT,
    STATE(19), 2,
      sym_attribute,
      aux_sym_source_repeat2,
  [209] = 3,
    ACTIONS(58), 1,
      sym_key,
    ACTIONS(77), 1,
      anon_sym_DASH_DASH_GT,
    STATE(7), 2,
      sym_attribute,
      aux_sym_source_repeat2,
  [220] = 3,
    ACTIONS(58), 1,
      sym_key,
    ACTIONS(79), 1,
      anon_sym_DASH_DASH_GT,
    STATE(7), 2,
      sym_attribute,
      aux_sym_source_repeat2,
  [231] = 2,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      aux_sym_text_token1,
  [240] = 2,
    ACTIONS(87), 1,
      anon_sym_EQ,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      anon_sym_DASH_DASH_GT,
      sym_key,
  [249] = 2,
    ACTIONS(91), 1,
      anon_sym_LT,
    ACTIONS(89), 3,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
      aux_sym_text_token1,
  [258] = 3,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(95), 1,
      anon_sym_EQ,
    ACTIONS(93), 2,
      anon_sym_field,
      sym_key,
  [269] = 1,
    ACTIONS(97), 3,
      ts_builtin_sym_end,
      anon_sym_DASH_DASH_GT,
      sym_key,
  [275] = 1,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      anon_sym_DASH_DASH_GT,
      sym_key,
  [281] = 1,
    ACTIONS(101), 3,
      ts_builtin_sym_end,
      anon_sym_DASH_DASH_GT,
      sym_key,
  [287] = 2,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(103), 2,
      anon_sym_field,
      sym_key,
  [295] = 2,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 2,
      anon_sym_field,
      sym_key,
  [303] = 2,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 2,
      anon_sym_field,
      sym_key,
  [311] = 2,
    ACTIONS(109), 1,
      anon_sym_SLASH,
    ACTIONS(111), 1,
      sym_tag,
  [318] = 1,
    ACTIONS(113), 1,
      sym_tag,
  [322] = 1,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 36,
  [SMALL_STATE(5)] = 54,
  [SMALL_STATE(6)] = 68,
  [SMALL_STATE(7)] = 82,
  [SMALL_STATE(8)] = 94,
  [SMALL_STATE(9)] = 108,
  [SMALL_STATE(10)] = 122,
  [SMALL_STATE(11)] = 136,
  [SMALL_STATE(12)] = 147,
  [SMALL_STATE(13)] = 156,
  [SMALL_STATE(14)] = 165,
  [SMALL_STATE(15)] = 176,
  [SMALL_STATE(16)] = 187,
  [SMALL_STATE(17)] = 198,
  [SMALL_STATE(18)] = 209,
  [SMALL_STATE(19)] = 220,
  [SMALL_STATE(20)] = 231,
  [SMALL_STATE(21)] = 240,
  [SMALL_STATE(22)] = 249,
  [SMALL_STATE(23)] = 258,
  [SMALL_STATE(24)] = 269,
  [SMALL_STATE(25)] = 275,
  [SMALL_STATE(26)] = 281,
  [SMALL_STATE(27)] = 287,
  [SMALL_STATE(28)] = 295,
  [SMALL_STATE(29)] = 303,
  [SMALL_STATE(30)] = 311,
  [SMALL_STATE(31)] = 318,
  [SMALL_STATE(32)] = 322,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat3, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat3, 2, 0, 0), SHIFT_REPEAT(30),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat3, 2, 0, 0), SHIFT_REPEAT(13),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat3, 2, 0, 0), SHIFT_REPEAT(13),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat2, 2, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_repeat2, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat2, 2, 0, 0), SHIFT_REPEAT(23),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_line, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_line, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat2, 2, 0, 0), SHIFT_REPEAT(21),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_line, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_line, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_marker, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker, 5, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_marker, 5, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_marker, 4, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_marker, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, 0, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 2),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3, 0, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [115] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_meshfox(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "meshfox",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
