import { useEffect, useRef, useState } from "react";
import type { CanvasNode, ExtraEdgeDto, NodeType } from "./types";
import type { NodePatch } from "./api";
import { basicSlug, translitSlug } from "./slug";
import { TagEditor } from "./TagEditor";

interface NodeSettingsProps {
  node: CanvasNode;
  /** Every other node in the document, for the "add incoming edge" picker
   * (titles to show, ids to send) — excludes `node` itself. */
  allNodes: CanvasNode[];
  /** Auto-save callback — fired (debounced) as fields change, and once
   * more on close to flush anything still pending. Doesn't close the
   * modal itself; only `onClose` does. */
  onChange: (patch: NodePatch) => void;
  /** Renames the node's own id — a separate, non-debounced, explicit
   * commit (see the ID field below), unlike every other field here: it
   * needs a uniqueness check and rewrites references in other nodes, so
   * it isn't just "one more patch field". Rejects (thrown error) if
   * `newId` is empty or already used by another node. */
  onRenameId: (oldId: string, newId: string) => Promise<void>;
  onClose: () => void;
}

/** JSON Canvas colors are either a hex string or a preset `"1"`–`"6"` — the
 * empty entry clears back to "no color". Purely a convenience shortcut
 * alongside the freeform text input, same idea as `VarsForm`'s `select`. */
const COLOR_SWATCHES = ["", "1", "2", "3", "4", "5", "6"];

/** How long to wait after the last field edit before auto-saving — long
 * enough that a burst of keystrokes (typing a title) doesn't send one
 * request per character, short enough that it still reads as "immediate". */
const AUTOSAVE_DELAY_MS = 700;

/**
 * Modal for one node's non-content settings: title, type, color, tags, a
 * file/link node's target, its extra incoming edges (`meshfox:edge`), and
 * deleting the node entirely — everything about a node except its Markdown
 * body, which the inline `NodeTextEditor` handles instead. Reuses
 * `VarsForm`'s modal/backdrop styling.
 *
 * Every edit auto-saves (debounced) rather than waiting on an explicit
 * Save button — consistent with every other edit in this app (add-child,
 * drag-connecting an edge) already persisting immediately. The full set of
 * fields is sent every time, not just whatever changed: re-sending a value
 * that hasn't changed is a harmless no-op server-side, and it means there's
 * no "diff against the original" to keep in sync as auto-save round-trips
 * update the canvas underneath this still-open modal.
 *
 * Deleting a node lives elsewhere — a dedicated button in the node's own
 * title bar (see MeshNode's trash icon and DeleteNodeDialog) rather than
 * here, since it needs to ask what happens to the node's children, which
 * doesn't fit this modal's auto-save-every-field shape.
 */
export function NodeSettings({ node, allNodes, onChange, onRenameId, onClose }: NodeSettingsProps) {
  const [title, setTitle] = useState(node.title);
  const [id, setId] = useState(node.id);
  const [idError, setIdError] = useState<string | null>(null);
  const [idSaving, setIdSaving] = useState(false);
  // The title as of when this modal opened (for this node — App.tsx keys
  // this component on `node.id`, so a successful rename remounts it fresh
  // with a new ref here too). Comparing the *current* id against this
  // fixed point (via `basicSlug`, the server's own non-transliterating
  // auto-slug) is what tells the suggestion hint below whether the id has
  // ever diverged from "whatever the server would auto-generate" — true
  // right after creation, and stays true across further title edits until
  // the user (or the hint's own "Apply") actually changes the id by hand.
  const initialTitle = useRef(node.title);
  const [nodeType, setNodeType] = useState<NodeType>(node.type ?? "text");
  const [color, setColor] = useState(node.color ?? "");
  const [target, setTarget] = useState(node.target ?? "");
  const [display, setDisplay] = useState<"link" | "code">(node.display ?? "link");
  const [lang, setLang] = useState(node.lang ?? "");
  const [interpreter, setInterpreter] = useState(node.interpreter ?? "");
  const [tags, setTags] = useState<string[]>(node.tags ?? []);
  const [extraParents, setExtraParents] = useState<ExtraEdgeDto[]>(node.extraParents ?? []);
  const [addSource, setAddSource] = useState("");

  const otherNodes = allNodes.filter((n) => n.id !== node.id);
  const addable = otherNodes.filter((n) => !extraParents.some((e) => e.from === n.id));
  const addSourceValue = addable.some((n) => n.id === addSource) ? addSource : addable[0]?.id ?? "";
  const titleOf = (nodeId: string) => allNodes.find((n) => n.id === nodeId)?.title ?? nodeId;

  // See `initialTitle` above: the hint only shows while the id still looks
  // auto-generated (never diverged), and only when the current title's
  // slug would actually be different from the id already there.
  const idLooksAutoGenerated = id === basicSlug(initialTitle.current);
  const suggestedId = translitSlug(title);
  const showIdSuggestion = idLooksAutoGenerated && suggestedId !== "" && suggestedId !== id;

  const commitId = async (candidate: string) => {
    const trimmed = candidate.trim();
    if (trimmed === "" || trimmed === node.id) {
      setId(node.id);
      setIdError(null);
      return;
    }
    setIdSaving(true);
    try {
      await onRenameId(node.id, trimmed);
      setIdError(null);
    } catch (e) {
      setId(node.id);
      setIdError(String(e));
    } finally {
      setIdSaving(false);
    }
  };

  // Guards against auto-saving a combination that's plainly incomplete
  // (still worth typing further on) rather than surfacing a 422 while the
  // user is mid-edit — a file/link node's target is required for its body
  // to be a valid single link.
  const isSaveable =
    title.trim() !== "" && (!(nodeType === "file" || nodeType === "link") || target.trim() !== "");

  const buildPatch = (): NodePatch => {
    const patch: NodePatch = { title, nodeType, color, tags, extraParents };
    if (nodeType === "file" || nodeType === "link") patch.target = target;
    if (nodeType === "file") {
      patch.display = display;
      patch.lang = lang;
      patch.interpreter = interpreter;
    }
    return patch;
  };

  const isFirstRender = useRef(true);
  const pendingSave = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false;
      return;
    }
    if (!isSaveable) return;
    pendingSave.current = setTimeout(() => {
      onChange(buildPatch());
      pendingSave.current = null;
    }, AUTOSAVE_DELAY_MS);
    return () => {
      if (pendingSave.current) clearTimeout(pendingSave.current);
    };
    // Deliberately keyed on the field values themselves, not `onChange`/
    // `buildPatch` (new closures every render) — this should only re-fire
    // when something the user actually edited changes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [title, nodeType, color, tags, target, display, lang, interpreter, extraParents, isSaveable]);

  const handleClose = () => {
    if (pendingSave.current) clearTimeout(pendingSave.current);
    if (isSaveable) onChange(buildPatch());
    onClose();
  };

  return (
    <div className="vars-modal-backdrop" onClick={handleClose}>
      <div className="vars-modal node-settings-modal" onClick={(e) => e.stopPropagation()}>
        <h3>Node settings</h3>
        <p className="vars-modal-hint">Changes save automatically.</p>
        <label className="vars-modal-field">
          <span>Title</span>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            autoFocus
          />
        </label>
        <label className="vars-modal-field">
          <span>ID</span>
          <input
            type="text"
            value={id}
            disabled={idSaving}
            onChange={(e) => {
              setId(e.target.value);
              setIdError(null);
            }}
            onBlur={(e) => commitId(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                (e.target as HTMLInputElement).blur();
              }
            }}
          />
        </label>
        {idError && <p className="node-settings-id-error">{idError}</p>}
        {showIdSuggestion && !idError && (
          <p className="node-settings-id-hint">
            Change id to "{suggestedId}"?{" "}
            <button
              type="button"
              onClick={() => {
                setId(suggestedId);
                commitId(suggestedId);
              }}
            >
              apply
            </button>
          </p>
        )}
        <label className="vars-modal-field">
          <span>Type</span>
          <select value={nodeType} onChange={(e) => setNodeType(e.target.value as NodeType)}>
            <option value="text">text</option>
            <option value="file">file</option>
            <option value="link">link</option>
            <option value="group">group</option>
          </select>
        </label>
        {(nodeType === "file" || nodeType === "link") && (
          <label className="vars-modal-field">
            <span>{nodeType === "file" ? "File path" : "URL"}</span>
            <input
              type="text"
              value={target}
              onChange={(e) => setTarget(e.target.value)}
              placeholder={nodeType === "file" ? "./path/to/file" : "https://…"}
            />
          </label>
        )}
        {nodeType === "file" && (
          <label className="vars-modal-field">
            <span>Display</span>
            <select value={display} onChange={(e) => setDisplay(e.target.value as "link" | "code")}>
              <option value="link">link</option>
              <option value="code">code (read-only preview)</option>
            </select>
          </label>
        )}
        {nodeType === "file" && display === "code" && (
          <label className="vars-modal-field">
            <span>Language</span>
            <input
              type="text"
              value={lang}
              onChange={(e) => setLang(e.target.value)}
              placeholder="auto-detect from file extension"
            />
          </label>
        )}
        {nodeType === "file" && (
          <label className="vars-modal-field">
            <span>Interpreter</span>
            <input
              type="text"
              value={interpreter}
              onChange={(e) => setInterpreter(e.target.value)}
              placeholder="e.g. python — makes this node runnable"
            />
          </label>
        )}
        <label className="vars-modal-field">
          <span>Color</span>
          <input
            type="text"
            value={color}
            onChange={(e) => setColor(e.target.value)}
            placeholder="hex, e.g. #ff8800, or a preset 1–6"
          />
          <div className="node-settings-swatches">
            {COLOR_SWATCHES.map((c) => (
              <button
                type="button"
                key={c || "none"}
                className="node-settings-swatch"
                data-swatch={c || "none"}
                title={c || "no color"}
                onClick={() => setColor(c)}
              />
            ))}
          </div>
        </label>
        <div className="vars-modal-field">
          <span>Tags</span>
          <TagEditor tags={tags} onChange={setTags} />
        </div>
        <div className="vars-modal-field">
          <span>Incoming edges (extra)</span>
          <p className="node-settings-edge-hint">
            Click an arrow on the canvas to set its text, color, line style, and arrowheads.
          </p>
          <div className="node-settings-chips">
            {extraParents.length === 0 && <em className="node-settings-empty-hint">none</em>}
            {extraParents.map((p) => (
              <span className="node-settings-chip" key={p.from}>
                {titleOf(p.from)}
                <button
                  type="button"
                  className="node-settings-chip-remove"
                  onClick={() => setExtraParents((prev) => prev.filter((x) => x.from !== p.from))}
                  title={`remove edge from ${titleOf(p.from)}`}
                >
                  ×
                </button>
              </span>
            ))}
          </div>
          {addable.length > 0 && (
            <div className="node-settings-add-edge">
              <select value={addSourceValue} onChange={(e) => setAddSource(e.target.value)}>
                {addable.map((n) => (
                  <option key={n.id} value={n.id}>
                    {n.title}
                  </option>
                ))}
              </select>
              <button
                type="button"
                onClick={() => setExtraParents((prev) => [...prev, { from: addSourceValue }])}
              >
                add edge
              </button>
            </div>
          )}
        </div>
        <div className="vars-modal-actions">
          <button type="button" onClick={handleClose}>
            close
          </button>
        </div>
      </div>
    </div>
  );
}
